app/dokumentacja/urls.py
from django.urls import path
from django.conf.urls.static import static

from .views import (
    DokumentDetailView,
    DodajDokument,
    DodajDokumentSeriall,
    dokumenty_branzy_inwestycji,
    SprawdzDokument,
    ajax_get_document_by_code,
    ajax_search_qrcode_by_image,
    WykazDokumentow,
    EdytujDokument,
    ZastapDokument,
    DokumentUpdateActionView,
    PobierzDokumentyView,
)

app_name = "dokumentacja"

urlpatterns = [
    # Dodaj dokument
    path("dodaj", DodajDokument.as_view(), name="dodaj_dokument"),
    path(
        "dodaj-dokumenty-seriall",
        DodajDokumentSeriall.as_view(),
        name="dodaj_dokumenty_seriall",
    ),
    path(
        "ajax/rysunki-branzy-inwestycji",
        dokumenty_branzy_inwestycji,
        name="ajax_dokumenty_branzy_inwestycji",
    ),
    # Sprawdź dokument
    path("sprawdz", SprawdzDokument.as_view(), name="sprawdz_dokument"),
    path(
        "ajax/get-document-by-code",
        ajax_get_document_by_code,
        name="ajax_get_document_by_code",
    ),
    path(
        "ajax/ajax-search-qrcode-by-image",
        ajax_search_qrcode_by_image,
        name="ajax_search_qrcode_by_image",
    ),
    # Wykaz dokumentów
    path("wykaz", WykazDokumentow.as_view(), name="wykaz_dokumentow"),
    # Dokument Detail
    path("dokument/<int:pk>", DokumentDetailView.as_view(), name="dokument_detail"),
    # Edytuj dokument
    path("dokument/<int:pk>/edytuj", EdytujDokument.as_view(), name="edytuj_dokument"),
    # Zastąp dokument
    path("dokument/<int:pk>/zastap", ZastapDokument.as_view(), name="zastap_dokument"),
    # Dokument akcje
    path("dokument/action", DokumentUpdateActionView.as_view(), name="dokument_action"),
]

app/panel/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

from .settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from .views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, Zarejestruj, index

urlpatterns = [
    path('zarejestruj/', Zarejestruj.as_view(), name='zarejestruj'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('dokumentacja/', include('dokumentacja.urls')),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
] + static(STATIC_URL, document_root=STATIC_ROOT) \
  + static(MEDIA_URL, document_root=MEDIA_ROOT)

app/dokumentacja/models.py
from os import path
from django.contrib.auth.decorators import login_required

from django.db import models
from django.db.models.fields import BooleanField
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager

from panel.settings import MEDIA_ROOT, MEDIA_URL
from dokumentacja.managers import DokumentCurrentManager

DOKUMENT_FILE_STORAGE = FileSystemStorage(
    location=path.join(MEDIA_ROOT, "documents"),
    base_url=path.join(MEDIA_URL, "documents"),
)


class User(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Inwestycja(models.Model):
    nazwa = models.CharField(max_length=30)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name = "Inwestycja"
        verbose_name_plural = "Inwestycje"

    def natural_key(self):
        return self.nazwa

    def get_absolute_url(self):
        return reverse("dokumentacja:inwestycja_detail", args=[str(self.id)])


class Branza(models.Model):
    nazwa = models.CharField(max_length=30)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name = "Branża"
        verbose_name_plural = "Branże"

    def natural_key(self):
        return self.nazwa


class Status(models.Model):
    nazwa = models.CharField(max_length=30)
    opis = models.TextField(blank=True)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name = "Status"
        verbose_name_plural = "Statusy"

    def natural_key(self):
        return self.nazwa


class Dokument(models.Model):
    file = models.FileField(storage=DOKUMENT_FILE_STORAGE)
    kod = models.CharField(max_length=5, unique=True, editable=False)
    inwestycja = models.ForeignKey(Inwestycja, on_delete=models.SET_NULL, null=True)
    branza = models.ForeignKey(
        Branza, verbose_name="Branża", on_delete=models.SET_NULL, null=True
    )
    oznaczenie = models.CharField(max_length=50)
    nazwa = models.CharField(max_length=200)
    opis = models.TextField(blank=True)
    komentarz = models.TextField(blank=True)
    data_dokumentu = models.DateField()
    data_dodania = models.DateField()
    dokument_nadrzedny = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Dokument nadrzędny",
    )
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    zarchiwizowany = models.BooleanField(default=False)

    objects = models.Manager()
    objects_current = DokumentCurrentManager()

    @property
    def dokumenty_podrzedne(self):
        dokumenty_qs = Dokument.objects.filter(dokument_nadrzedny=self)
        return dokumenty_qs

    @property
    def url_change(self):
        return reverse("dokumentacja:edytuj_dokument", args=[str(self.pk)])

    def __str__(self):
        return self.nazwa + " (" + self.oznaczenie + ")"

    class Meta:
        verbose_name = "Dokument"
        verbose_name_plural = "Dokumenty"

    def natural_key(self):
        return self.nazwa

    def get_absolute_url(self):
        return reverse("dokumentacja:dokument_detail", args=[str(self.pk)])

app/dokumentacja/forms.py
from django import forms
from django.forms import fields

from .models import Dokument, Inwestycja


class DodajDokumentForm(forms.ModelForm):
    class Meta:
        model = Dokument
        fields = "__all__"
        exclude = [
            "status",
            "zarchiwizowany",
        ]


class EdytujDokumentForm(forms.ModelForm):
    class Meta:
        model = Dokument
        fields = "__all__"
        exclude = [
            "file",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if "instance" in kwargs:
            instance = kwargs["instance"]
            inwestycja = instance.inwestycja
            branza = instance.branza
            dokumenty_nadrzedne = Dokument.objects.filter(
                inwestycja=inwestycja, branza=branza
            )
            self.fields["dokument_nadrzedny"] = forms.ModelChoiceField(
                queryset=dokumenty_nadrzedne, required=False
            )

app/dokumentacja/views.py
from datetime import date
import json
from random import choice
import string
from os import path
import sys
import re

from django.core import serializers
from django.core.exceptions import PermissionDenied
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.contrib.auth.models import Permission
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse, FileResponse, HttpResponseRedirect
from django.http.response import Http404
from urllib.parse import urlencode
from django.shortcuts import render, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt

from .models import (
    Inwestycja,
    Branza,
    Dokument,
    Status,
    User,
)
from .models import DOKUMENT_FILE_STORAGE
from .forms import (
    DodajDokumentForm,
    EdytujDokumentForm,
)
from .src import add_qrcode_to_pdf
from .extension import Plural


class DodajDokument(View):
    form_class = DodajDokumentForm
    template_name = "dokumentacja/dodaj-dokument.html"

    @method_decorator(login_required)
    @method_decorator(permission_required("dokumentacja.add_dokument"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def _generuj_kod(self):
        kod = ""
        while True:
            kod = "".join(
                choice(string.ascii_letters + string.digits) for i in range(5)
            )
            queryset = Dokument.objects.filter(kod=kod)
            if not bool(queryset):
                break
        return kod

    def get(self, request, *args, **kwargs):
        initial = request.GET.dict()
        initial.update({"data_dodania": date.today().isoformat()})
        form = self.form_class(initial=initial)
        print(initial)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        kod = self._generuj_kod()
        form = self.form_class(request.POST, request.FILES)
        form.fields["data_dodania"].value = date.today().isoformat()
        filename = request.FILES.get("file").name
        if form.is_valid():
            dokument = form.save(commit=False)
            dokument.kod = kod
            dokument.data_dodania = date.today().isoformat()
            AKTUALNY = Status.objects.get(nazwa="Aktualny")
            dokument.status = AKTUALNY
            dokument.save()

            dokument_path = path.join(
                DOKUMENT_FILE_STORAGE.location, dokument.file.path
            )
            qr_x = request.POST.get("qr_x")
            qr_y = request.POST.get("qr_y")
            add_qrcode_to_pdf.PdfDoc(
                path=dokument_path, qr_code=dokument.kod, qr_coords=(qr_x, qr_y)
            )

            dokument.save()
            return FileResponse(dokument.file, as_attachment=True, filename=filename)
        print(form.errors)
        print(form.fields)
        return render(request, self.template_name, {"form": form})


class DodajDokumentSeriall(View):
    form_class = DodajDokumentForm
    template_name = "dokumentacja/dodaj-dokument.html"

    def _generuj_kod(self):
        kod = ""
        while True:
            kod = "".join(
                choice(string.ascii_letters + string.digits) for i in range(5)
            )
            queryset = Dokument.objects.filter(kod=kod)
            if not bool(queryset):
                break
        return kod

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        kod = self._generuj_kod()
        post_data = request.POST.dict()
        post_data["inwestycja"] = Inwestycja.objects.get(nazwa=post_data["inwestycja"])
        post_data["branza"] = Branza.objects.get(nazwa=post_data["branza"])
        form = self.form_class(post_data, request.FILES)
        filename = request.FILES.get("file").name
        print(form.is_valid())
        print(form.errors)
        if form.is_valid():
            dokument = form.save(commit=False)
            dokument.kod = kod
            dokument.data_dodania = date.today().isoformat()
            AKTUALNY = Status.objects.get(nazwa="Aktualny")
            dokument.status = AKTUALNY
            dokument.save()

            dokument_path = path.join(
                DOKUMENT_FILE_STORAGE.location, dokument.file.path
            )
            qr_x = request.POST.get("qr_x")
            qr_y = request.POST.get("qr_y")
            add_qrcode_to_pdf.PdfDoc(
                path=dokument_path, qr_code=dokument.kod, qr_coords=(qr_x, qr_y)
            )

            dokument.save()
            return FileResponse(dokument.file, as_attachment=True, filename=filename)
        return render(request, self.template_name, {"form": form})


class ZastapDokument(View):

    template_name = "dokumentacja/zastap-dokument.html"

    @method_decorator(login_required)
    @method_decorator(permission_required("dokumentacja.change_dokument"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk, *args, **kwargs):
        try:
            dokument = Dokument.objects.get(pk=pk)
        except:
            return render(
                request,
                template_name=self.template_name,
                context={"errors": ["Nie znaleziono dokumentu"]},
            )

        try:
            STATUS_NIEAKTUALNY = Status.objects.get(nazwa="Nieaktualny")
        except:
            return render(
                request,
                template_name=self.template_name,
                context={"errors": ['Nie znaleziono statusu "Nieaktualny"']},
            )

        dokument.status = STATUS_NIEAKTUALNY

        try:
            dokument.save()
        except Exception as e:
            return render(
                request, template_name=self.template_name, context={"errors": [str(e)]}
            )

        base_url = reverse("dokumentacja:dodaj_dokument")
        query_string = urlencode(
            {
                "inwestycja": dokument.inwestycja.pk,
                "branza": dokument.branza.pk,
                "oznaczenie": dokument.oznaczenie,
                "nazwa": dokument.nazwa,
            }
        )

        url = "{}?{}".format(base_url, query_string)
        return HttpResponseRedirect(url)


class EdytujDokument(View):

    form_class = EdytujDokumentForm
    template_name = "dokumentacja/edytuj-dokument.html"

    @method_decorator(login_required)
    @method_decorator(permission_required("dokumentacja.change_dokument"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk, *args, **kwargs):
        dokument = Dokument.objects.get(pk=pk)
        form = self.form_class(instance=dokument)
        return render(request, template_name=self.template_name, context={"form": form})

    def post(self, request, pk, *args, **kwargs):
        dokument = dokument = Dokument.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=dokument)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse("dokumentacja:dokument_detail", args=(pk,))
            )
        return render(request, template_name=self.template_name, context={"form": form})


def dokumenty_branzy_inwestycji(request):
    if request.is_ajax and request.method == "POST":
        pk_inwestycja = request.POST.dict()["pk_inwestycja"]
        pk_branza = request.POST.dict()["pk_branza"]
        dokumenty_nadrzedne = Dokument.objects.filter(inwestycja=pk_inwestycja).filter(
            branza=pk_branza
        )
        ser_dokumenty_nadrzedne = serializers.serialize("json", dokumenty_nadrzedne)
        return JsonResponse(
            {"dokumenty_nadrzedne": ser_dokumenty_nadrzedne}, status=200
        )


class DokumentDetailView(DetailView):
    model = Dokument
    template_name = "dokumentacja/dokument_detail.html"

    @method_decorator(login_required)
    @method_decorator(permission_required("dokumentacja.view_dokument"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SprawdzDokument(View):
    template_name = "dokumentacja/sprawdz-dokument.html"

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name, context={})


def ajax_get_document_by_code(request):
    if request.is_ajax and request.method == "GET":
        kod = request.GET.get("kod")
        try:
            dokument = Dokument.objects.get(kod=kod)
        except Exception as e:
            return JsonResponse({"error": "Nie znaleziono dokumentu"}, status=200)

        ser_data = {
            "dokument": serializers.serialize(
                "json", [dokument], use_natural_foreign_keys=True
            )
        }
        dokument_nadrzedny = dokument.dokument_nadrzedny
        if dokument_nadrzedny:
            ser_data.update(
                {
                    "dokument_nadrzedny": serializers.serialize(
                        "json",
                        [dokument_nadrzedny],
                    )
                }
            )
        else:
            ser_data.update({"dokument_nadrzedny": None})

        dokumenty_podrzedne = Dokument.objects.filter(dokument_nadrzedny=dokument.pk)
        if dokumenty_podrzedne:
            ser_data.update(
                {
                    "dokumenty_podrzedne": serializers.serialize(
                        "json", dokumenty_podrzedne
                    )
                }
            )
        else:
            ser_data.update({"dokumenty_podrzedne": None})

        ser_data.update({"url_change": json.dumps([dokument.url_change])})

app/templates/dokumentacja/dodaj-dokument-form.html
<!-- Plik -->
{% with field=form.file %}
<div class="mt-2 form-row">
    <input type="file" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" required>
</div>
{% endwith %}
<!-- Inwestycja -->
{% with field=form.inwestycja %}
<div class="mt-2 form-row">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <select name="{{ field.name }}" id="id_inwestycja" class="form-select  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" required>
        {% for item in field %}
            {{item}}
        {% endfor %}
        </select>
</div>
{% endwith %}
<!-- Branża -->
{% with field=form.branza %}
<div class="mt-2 form-row">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <select name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-select  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" required>
        {% for item in field %}
            {{item}}
        {% endfor %}
        </select>
</div>
{% endwith %}
<!-- Oznaczenie -->
{% with field=form.oznaczenie %}
<div class="mt-2">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <input name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" value="{{ field.value|default:'' }}" required/>
</div>
{% endwith %}
<!-- Nazwa -->
{% with field=form.nazwa %}
<div class="mt-2">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <input name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" value="{{ field.value|default:'' }}" required/>
</div>
{% endwith %}
<!-- Opis -->
{% with field=form.opis %}
<div class="mt-2">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <textarea name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" value="{{ field.value }}"></textarea>
</div>
{% endwith %}
<!-- Data rysunku -->
{% with field=form.data_dokumentu %}
<div class="mt-2">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <input type="date" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" value="{{ field.value }}" required/>
</div>
{% endwith %}
<!-- Data dodania -->
{% with field=form.data_dodania %}
<div class="mt-2">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <input type="date" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control" value="{{ field.value }}" readonly/>
</div>
{% endwith %}
<!-- Rysunek nadrzędny -->
{% with field=form.dokument_nadrzedny %}
<div class="mt-2 form-row">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <select name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-select  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}">
        {% for item in field %}
            {{item}}
        {% endfor %}    
        </select>
</div>
{% endwith %}
<!-- Komentarz -->
{% with field=form.komentarz %}
<div class="mt-2">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <textarea name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control  {% if field.errors %}is-invalid{% elif form.errors %}is-valid{% endif %}" value="{{ field.value }}"></textarea>
</div>
<!-- Dodatkowe pola -->
<input type="hidden" name="qr_x" id="qr_x" />
<input type="hidden" name="qr_y" id="qr_y" />
{% endwith %}

app/templates/dokumentacja/dodaj-dokument.html
{% extends "base.html" %} 
{% load static %} {% block title %} Dodaj dokument {% endblock %}{% block extrastyle %}
<link rel="stylesheet" href="{% static 'dokumentacja/dodaj-dokument/css/dodaj-dokument.css' %}"> {% endblock %} {% block extrahead %}
<script src="{% static 'modules/pdfjs/pdf.js' %}"></script>
<script src="{% static 'modules/pdfjs/pdf.worker.js' %}"></script>
{% endblock %} {% block container_class %} container-fluid {% endblock %} {% block content %} {% if error_message %}
<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="w-100 mt-3"></div>

<div class="row">
  <div class="col-12 col-xl-4">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'dokumentacja/dodaj-dokument-form.html' %}
      <input type="submit" class="btn btn-primary w-100 mt-3" value="Dodaj" />
    </form>
  </div>

  <div class="col-12 mt-2 col-xl-8 mt-xl-0">
    <div id="pdf_wrapper">
      <img id="sample_qr" src="{% static 'dokumentacja/dodaj-dokument/img/qr.png' %}">
      <canvas id="pdf_render"></canvas>
    </div>
  </div>
</div>

<div class="w-100 mt-3"></div>

<script>
  var url_ajax_rysunki_branzy = "{% url 'dokumentacja:ajax_dokumenty_branzy_inwestycji' %}"
</script>
<script src="{% static 'dokumentacja/dodaj-dokument/js/rysunki-nadrzedne.js' %}"></script>
<script src="{% static 'dokumentacja/dodaj-dokument/js/dodaj-dokument.js' %}"></script>
{% endblock content %}
</body>

</html>

app/templates/dokumentacja/edytuj-dokument.html
{% extends 'base.html' %} {% block title %} Edytuj dokument {% endblock title %}


{% block content %}
    
<div class="col-12 col-xl-4 mx-auto border rounded-3 p-3 mt-3 bg-white">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'dokumentacja/edytuj-dokument-form.html' %}
      <input type="submit" class="btn btn-secondary w-100 mt-3" value="Zapisz" />
    </form>
  </div>



{% endblock content %}
    

app/templates/dokumentacja/sprawdz-dokument.html
{% extends 'base.html' %} {% block title %} Sprawdź dokument{% endblock title %}

{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'dokumentacja/sprawdz-dokument/css/sprawdz-dokument.css' %}">
{% endblock extrastyle %}
{% block extrahead %}
    <script src="{% static 'modules/qcode-decoder/build/qcode-decoder.min.js' %}"></script>
    <script src="{% static 'dokumentacja/sprawdz-dokument/js/sprawdz-dokument-ajax.js' %}"></script>
{% endblock extrahead %}




{% block content %}

<div class="w-100 mt-3"></div>
<div class="row">
    <div class="col-12 col-md-6 col-lg-4">
        <div id="search-container" class="">
            <div id="search-toogle-container" class="row mt-2">
                <div class="col text-center">
                    <input type="radio" class="btn-check" name="options" id="set-video" autocomplete="off">
                    <label class="btn btn-secondary btn-lg" for="set-video"><i class="bi bi-camera-video"></i></label>
                </div>
                
                <div class="col text-center">
                    <input type="radio" class="btn-check" name="options" id="set-file" autocomplete="off" checked>
                    <label class="btn btn-secondary btn-lg" for="set-file"><i class="bi bi-folder2-open"></i></label>
                </div>
            </div>
            <div id="document-source-container" class="mt-2">
                <div id="document-source-video">
                    <div id="video-select-container" class="w-100 my-2">
                        <label class="mb-1">Wybierz kamerę</label>
                        <select name="camera" id="video-select" class="form-select"></select>
                    </div>
                    <video id="v" autoplay ></video>
                    <div id="video-help" style="display: none;">
                        <input class="btn btn-outline-primary" type="button" value="Odśwież">
                    </div>
                </div>
                <div id="document-source-file">
                    <input id="select-file-btn" type="file" accept="application/pdf" style="display:none;">
                    <label class="text-center" for="select-file-btn">
                        <div id="select-file-label">
                            <i class="bi bi-cloud-arrow-up" style="font-size:80px;"></i>
                            <div class="w-100"> </div>
                            Wybierz plik lub przeciągnij i upuść
                        </div>
                        <div id="render-spinner" style="display:none">
                            <div class="spinner-border m-4" style="width: 68px; height: 68px;"></div>
                            <div class="w-100"> </div>
                            Trwa weryfikacja dokumentu...
                        </div>
                    </label>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-12 col-md-6 col-lg-8 ">
        <div id="result-container" class="">
            <div class="w-100" id="result-help"></div>
            <table class="table">
                <tr>
                    <td>Inwestycja:</td><td id="inwestycja-val"></td>
                </tr>
                <tr>
                    <td>Branża:</td><td id="branza-val"></td>
                </tr>
                <tr>
                    <td>Oznaczenie:</td><td id="oznaczenie-val"></td>
                </tr>
                <tr>
                    <td>Nazwa:</td><td id="nazwa-val"></td>
                </tr>
                <tr>
                    <td>Status:</td><td id="status-val"></td>
                </tr>
            </table>
            <div class="w-100 mt-2" style="text-align:right;">
                <a class="btn btn-primary" id="result-button-edit" href="#" role="button">Edytuj</a>
                <a class="btn btn-success" id="result-button-details" href="#" role="button">Szczegóły</a>
            </div>
        </div>
    </div>
</div>    




<canvas id="video-canvas" style="display: none; width: 800px; height: 600px;" width="800" height="600"></canvas>

<script src="{% static 'dokumentacja/sprawdz-dokument/js/video-input.js' %}"></script>
<script src="{% static 'dokumentacja/sprawdz-dokument/js/sprawdz-dokument.js' %}"></script>

<script>
    var url_ajax_get_document_by_code = "{% url 'dokumentacja:ajax_get_document_by_code' %}" 
    var url_ajax_search_qrcode_by_image = "{% url 'dokumentacja:ajax_search_qrcode_by_image' %}" 
</script>

{% endblock content %}