app/dokumentacja/urls.py
from django.urls import path
from django.conf.urls.static import static

from .views import (
    DokumentDetailView,
    DodajDokument,
    DodajDokumentSeriall,
    dokumenty_branzy_inwestycji,
    SprawdzDokument,
    ajax_get_document_by_code,
    ajax_search_qrcode_by_image,
    WykazDokumentow,
    EdytujDokument,
    ZastapDokument,
    DokumentUpdateActionView,
    PobierzDokumentyView,
)

app_name = "dokumentacja"

urlpatterns = [
    # Dodaj dokument
    path("dodaj", DodajDokument.as_view(), name="dodaj_dokument"),
    path(
        "dodaj-dokumenty-seriall",
        DodajDokumentSeriall.as_view(),
        name="dodaj_dokumenty_seriall",
    ),
    path(
        "ajax/rysunki-branzy-inwestycji",
        dokumenty_branzy_inwestycji,
        name="ajax_dokumenty_branzy_inwestycji",
    ),
    # Sprawdź dokument
    path("sprawdz", SprawdzDokument.as_view(), name="sprawdz_dokument"),
    path(
        "ajax/get-document-by-code",
        ajax_get_document_by_code,
        name="ajax_get_document_by_code",
    ),
    path(
        "ajax/ajax-search-qrcode-by-image",
        ajax_search_qrcode_by_image,
        name="ajax_search_qrcode_by_image",
    ),
    # Wykaz dokumentów
    path("wykaz", WykazDokumentow.as_view(), name="wykaz_dokumentow"),
    # Dokument Detail
    path("dokument/<int:pk>", DokumentDetailView.as_view(), name="dokument_detail"),
    # Edytuj dokument
    path("dokument/<int:pk>/edytuj", EdytujDokument.as_view(), name="edytuj_dokument"),
    # Zastąp dokument
    path("dokument/<int:pk>/zastap", ZastapDokument.as_view(), name="zastap_dokument"),
    # Dokument akcje
    path("dokument/action", DokumentUpdateActionView.as_view(), name="dokument_action"),
]

app/panel/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

from .settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from .views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, Zarejestruj, index

urlpatterns = [
    path('zarejestruj/', Zarejestruj.as_view(), name='zarejestruj'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('dokumentacja/', include('dokumentacja.urls')),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
] + static(STATIC_URL, document_root=STATIC_ROOT) \
  + static(MEDIA_URL, document_root=MEDIA_ROOT)

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">

<head>
    <title>{% block title %}Panel zarządzania projektami{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load static %} {% block stylesheet %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- Własne CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav_topbar.css' %}"> {% endblock stylesheet %} {% block extrastyle %}{% endblock %}
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block extrahead %}{% endblock %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}" /> {% block blockbots %}
    <meta name=" robots " content="NONE,NOARCHIVE ">{% endblock %}
</head>

<body>
    {% block nav-sidebar %} {% include "nav_topbar.html" %} {% endblock %}

    <div class="{% block container_class %} container {% endblock %} ">
        {% block content %} {% endblock %}
    </div>

    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %} "></script>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %} {% block title %} Strona główna {% endblock title %}

app/templates/nav_topbar.html
<nav id="main-navbar" class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Panel zarządzania projektami</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/">Strona główna</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dokumentacja
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'dokumentacja:dodaj_dokument' %}">Dodaj</a></li>
                        <li><a class="dropdown-item" href="{% url 'dokumentacja:sprawdz_dokument' %}">Sprawdź</a></li>
                        <li><a class="dropdown-item" href="{% url 'dokumentacja:wykaz_dokumentow' %}">Wykaz</a></li>
                        <!--            <li><hr class="dropdown-divider"></li>-->
                        <!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Konto
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'zarejestruj' %}">Zarejestruj</a></li>
                        <li><a class="dropdown-item" href="{% url 'login' %}">Zaloguj</a></li>
                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Zmień hasło</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Wyloguj</a></li>
                        <!--            <li><hr class="dropdown-divider"></li>-->
                        <!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
                    </ul>
                </li>
                <!--        <li class="nav-item">-->
                <!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
                <!--        </li>-->
            </ul>
            <form class="d-flex">
                <div id="user-tools">
                    {% block welcome-msg %} {% if user.is_authenticated %} Jesteś zalogowany jako <strong> {% firstof user.get_short_name user.get_username %}</strong>.
                    <a href="{% url 'logout' %}">/Wyloguj/</a> {% else%} Nie jesteś zalogowany
                    <a href="{% url 'login' %}">/Zaloguj/</a> {% endif %} {% endblock welcome-msg %}
                </div>
            </form>
        </div>
    </div>
</nav>